apiVersion: v1
kind: Pod
metadata:
  name: tcs-llyods-frontend-ui1 
  labels:
    app: tcs-llyods-frontend-ui1 
spec:
  containers:
    - name: tcs-llyods-frontend-ui1 
      image: suvin241/tcs-llyods-frontend-ui1:latest
      ports:
        - containerPort: 8081
        
apiVersion: v1
kind: Pod
metadata:
  name: tcs-llyods-backend-s1 
  labels:
    app: tcs-llyods-backend-s1 
spec:
  containers:
    - name: tcs-llyods-backend-s1 
      image: suvin241/tcs-llyods-backend-s1:latest
      ports:
        - containerPort: 8082

