kind: Service
apiVersion: v1
metadata:
  name: frontend-ui2
spec:
  selector:
    app: frontend-ui2 
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: LoadBalancer   
  
kind: Service
apiVersion: v1
metadata:
  name: backend-s2
spec:
  selector:
    app: backend-s2
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
  type: LoadBalancer   


