kind: Service
apiVersion: v1
metadata:
  name: frontend-ui2
spec:
  selector:
    app: frontend-ui2 
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 8081
    name: frontend
  type: LoadBalancer    


